BAPI_MAP = {
    "GET_OPEN_ITEMS": "BAPI_AP_ACC_GETOPENITEMS",
    "GET_CURRENT_BALANCE": "BAPI_AP_ACC_GETCURRENTBALANCE",
    "GET_KEYDATE_BALANCE": "BAPI_AP_ACC_GETKEYDATEBALANCE",
    "GET_VENDOR_DETAIL": "BAPI_VENDOR_GETDETAIL",
    "FIND_VENDOR": "BAPI_VENDOR_FIND",
    "CHECK_VENDOR": "BAPI_VENDOR_EXISTENCECHECK",
    "CREATE_VENDOR": "BAPI_VENDOR_CREATE",
    "EDIT_VENDOR": "BAPI_VENDOR_EDIT",
}
